import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/rendering.dart';
import '../theme/app_theme.dart';
import '../services/encryption_service.dart';

class GenerateScreen extends StatefulWidget {
  const GenerateScreen({super.key});

  @override
  State<GenerateScreen> createState() => _GenerateScreenState();
}

class _GenerateScreenState extends State<GenerateScreen> {
  final _urlController = TextEditingController();
  final _passwordController = TextEditingController();
  final _confirmController = TextEditingController();
  final _encryptionService = EncryptionService();
  final _formKey = GlobalKey<FormState>();
  final _qrKey = GlobalKey();

  bool _protect = false;
  String _errorCorrection = 'M';
  int _boxSize = 200;
  String? _qrData;
  String? _savedPath;
  bool _generated = false;
  bool _saving = false;

  final _errorLevels = ['L', 'M', 'Q', 'H'];

  String _getQrText() {
    final url = _urlController.text.trim();
    if (!_protect || _passwordController.text.isEmpty) return url;

    return _encryptionService.encrypt(url, _passwordController.text);
  }

  Future<void> _generate() async {
    final url = _urlController.text.trim();
    if (url.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a URL or text')),
      );
      return;
    }

    if (_protect) {
      if (_passwordController.text.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please enter a password')),
        );
        return;
      }
      if (_passwordController.text != _confirmController.text) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Passwords do not match')),
        );
        return;
      }
    }

    setState(() {
      _qrData = _getQrText();
      _generated = true;
      _savedPath = null;
    });
  }

  Future<void> _save() async {
    if (_qrData == null) return;
    setState(() => _saving = true);

    try {
      final boundary = _qrKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) return;

      final image = await boundary.toImage(pixelRatio: 3);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) return;

      final dir = await getApplicationDocumentsDirectory();
      final ts = DateTime.now().millisecondsSinceEpoch;
      final filename = 'QR_$ts.png';
      final file = File('${dir.path}/$filename');
      await file.writeAsBytes(byteData.buffer.asUint8List());

      final encDir = Directory('${dir.path}/QR_Codes');
      if (!await encDir.exists()) await encDir.create();
      final dest = await file.copy('${encDir.path}/$filename');
      await file.delete();

      setState(() => _savedPath = dest.path);

      if (_protect && _passwordController.text.isNotEmpty) {
        final keyFile = File(dest.path.replaceAll('.png', '.key'));
        await keyFile.writeAsString(_passwordController.text);
      }

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('QR code saved successfully')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error saving: $e')),
      );
    } finally {
      setState(() => _saving = false);
    }
  }

  void _share() async {
    if (_savedPath == null) return;
    await Share.shareXFiles([XFile(_savedPath!)],
        text: 'QR Code generated by QR Generator');
  }

  @override
  void dispose() {
    _urlController.dispose();
    _passwordController.dispose();
    _confirmController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Card(
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Enter URL or text',
                        style: Theme.of(context)
                            .textTheme
                            .titleSmall
                            ?.copyWith(fontWeight: FontWeight.bold)),
                    const SizedBox(height: 10),
                    TextFormField(
                      controller: _urlController,
                      decoration: const InputDecoration(
                        hintText: 'https://example.com',
                        prefixIcon: Icon(Icons.link),
                      ),
                      onFieldSubmitted: (_) => _generate(),
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Error Correction',
                                  style: Theme.of(context)
                                      .textTheme
                                      .bodySmall
                                      ?.copyWith(color: AppTheme.textSecondary)),
                              const SizedBox(height: 6),
                              DropdownButtonFormField<String>(
                                value: _errorCorrection,
                                items: _errorLevels
                                    .map((e) => DropdownMenuItem(
                                        value: e,
                                        child: Text('$e (${_levelName(e)})')))
                                    .toList(),
                                onChanged: (v) =>
                                    setState(() => _errorCorrection = v!),
                                decoration: const InputDecoration(
                                  contentPadding: EdgeInsets.symmetric(
                                      horizontal: 12, vertical: 10),
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('QR Size',
                                  style: Theme.of(context)
                                      .textTheme
                                      .bodySmall
                                      ?.copyWith(color: AppTheme.textSecondary)),
                              const SizedBox(height: 6),
                              DropdownButtonFormField<int>(
                                value: _boxSize,
                                items: [160, 200, 260]
                                    .map((s) => DropdownMenuItem(
                                        value: s,
                                        child: Text(_sizeName(s))))
                                    .toList(),
                                onChanged: (v) =>
                                    setState(() => _boxSize = v!),
                                decoration: const InputDecoration(
                                  contentPadding: EdgeInsets.symmetric(
                                      horizontal: 12, vertical: 10),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    CheckboxListTile(
                      title: const Text('Protect with password'),
                      value: _protect,
                      onChanged: (v) => setState(() => _protect = v!),
                      controlAffinity: ListTileControlAffinity.leading,
                      contentPadding: EdgeInsets.zero,
                      activeColor: AppTheme.protectedTag,
                    ),
                    if (_protect) ...[
                      const SizedBox(height: 4),
                      TextFormField(
                        controller: _passwordController,
                        obscureText: true,
                        decoration: const InputDecoration(
                          hintText: 'Enter password',
                          prefixIcon: Icon(Icons.lock_outline),
                        ),
                      ),
                      const SizedBox(height: 12),
                      TextFormField(
                        controller: _confirmController,
                        obscureText: true,
                        decoration: const InputDecoration(
                          hintText: 'Confirm password',
                          prefixIcon: Icon(Icons.lock_outline),
                        ),
                      ),
                    ],
                    const SizedBox(height: 20),
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton.icon(
                        onPressed: _generate,
                        icon: const Icon(Icons.qr_code),
                        label: const Text('Generate'),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          if (_generated && _qrData != null) ...[
            const SizedBox(height: 20),
            Card(
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  children: [
                    Row(
                      children: [
                        Text('Preview',
                            style: Theme.of(context)
                                .textTheme
                                .titleSmall
                                ?.copyWith(fontWeight: FontWeight.bold)),
                        const Spacer(),
                        if (_protect)
                          Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 8, vertical: 4),
                            decoration: BoxDecoration(
                              color: AppTheme.protectedTag,
                              borderRadius: BorderRadius.circular(6),
                            ),
                            child: const Text('PROTECTED',
                                style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 10,
                                    fontWeight: FontWeight.bold)),
                          ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    RepaintBoundary(
                      key: _qrKey,
                      child: Container(
                        padding: const EdgeInsets.all(16),
                        color: Colors.white,
                        child: QrImageView(
                          data: _qrData!,
                          version: QrVersions.auto,
                          errorCorrectionLevel:
                              _parseErrorLevel(_errorCorrection),
                          size: _boxSize.toDouble(),
                          backgroundColor: Colors.white,
                        ),
                      ),
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton.icon(
                            onPressed: _saving ? null : _save,
                            icon: _saving
                                ? const SizedBox(
                                    width: 16,
                                    height: 16,
                                    child: CircularProgressIndicator(
                                        strokeWidth: 2))
                                : const Icon(Icons.save_alt),
                            label: const Text('Save'),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: OutlinedButton.icon(
                            onPressed: _savedPath != null ? _share : null,
                            icon: const Icon(Icons.share),
                            label: const Text('Share'),
                          ),
                        ),
                      ],
                    ),
                    if (_savedPath != null) ...[
                      const SizedBox(height: 12),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: AppTheme.warningBg,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Text(
                          _savedPath!,
                          style: Theme.of(context)
                              .textTheme
                              .bodySmall
                              ?.copyWith(color: AppTheme.warningText),
                        ),
                      ),
                    ],
                  ],
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  String _levelName(String level) {
    switch (level) {
      case 'L':
        return 'Low';
      case 'M':
        return 'Medium';
      case 'Q':
        return 'Quartile';
      case 'H':
        return 'High';
      default:
        return '';
    }
  }

  String _sizeName(int size) {
    switch (size) {
      case 160:
        return 'Small';
      case 200:
        return 'Medium';
      case 260:
        return 'Large';
      default:
        return '';
    }
  }

  int _parseErrorLevel(String level) {
    switch (level) {
      case 'L':
        return 0;
      case 'M':
        return 1;
      case 'Q':
        return 2;
      case 'H':
        return 3;
      default:
        return 1;
    }
  }
}
